#include <QCoreApplication>
#include <channel.h>
#include <kernel.h>
#include <dataloader.h>
#include <filter.h>

#include <random>
#include <time.h>
#include <QDebug>
#include <QtDebug>


int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);


    // Also amount of output channels.
    int kernelAmount = 32;

    int filterAmount = 28;
    QVector<Kernel> kernelArray = QVector<Kernel>(kernelAmount, Kernel(filterAmount, kernelAmount));

    // qDebug() << kernelArray.size();
    for (Kernel i : kernelArray) {
        for (Filter j : i.content) {
            j.reset(32);
        }
    }
    kernelArray[0].printContent();

    mt19937 gen(time(NULL)); // mersenne_twister_engine seeded with rd()
    uniform_real_distribution<double> dis(-1.0, 1.0);
    for (int n = 0; n < 10; ++n) {
            // Use dis to transform the random unsigned int generated by gen into a
            // double in [1, 2). Each call to dis(gen) generates a new random double
            std::cout << dis(gen) << ' ';
        }

    // cout << "Clock: " << time(NULL);

    /*
    Kernel myKern(2);
    myKern.printContent();
    // myKern.reset();
    // myKern.printContent();
    */

    /*
    Filter myFilter(28);

    DataLoader myLoader;
    myLoader.loadBatch();
    QVector<int> data = myLoader.convertStringData();

    myChan.fill(data);
    myChan.pad();
    // myChan.printContent();
    (myChan.applyFilter(myFilter)).printContent();
    */

    return a.exec();
}
